# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts v3.0.0
dependencies:
  - OpenZeppelin/openzeppelin-contracts@3.0.0

# path remapping to support OpenZepplin imports with NPM-style path
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@3.0.0"
networks:
  default: polygon-main-fork

  polygon-main:
    aave_lending_pool_v2: "0xd05e3E715d945B59290df0ae8eF85c1BdB684744"
    weth: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270"
    dai: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
  polygon-main-fork:
    aave_lending_pool_v2: "0xd05e3E715d945B59290df0ae8eF85c1BdB684744"
    weth: "0x0d500b1d8e8ef31e21c99d1db9a6444d3adf1270"
    dai: "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"

wallets:
  from_key: ${PRIVATE_KEY}
  from_mnemonic: ${MNEMONIC}
